name: NodeSource Certification
on: pull_request

jobs:
  ncm_report:
    runs-on: ubuntu-latest
    name: N|S -> NCM Pipeline
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: NCM Report
        id: report
        uses: nodesource/ncm-report-github-action@master
        with:
          token: ${{ secrets.NCM_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
