name: NodeSource Certification
on: pull_request

jobs:
  ncm_report:
    runs-on: ubuntu-latest
    name: N|S -> NCM Pipeline
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Annotate
        uses: Attest/annotations-action@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          input: './annotations.json'
          path: './annotations.json'
          title: 'Annotate Files'
      - name: NCM Report
        id: report
        uses: nodesource/ncm-report-github-action@v1.2.0
        with:
          token: ${{ secrets.NCM_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_job_name: N|S -> NCM Pipeline
